#
# Configuration to use when the application is terminating TLS in the
# spring boot application itself.
#
spring:
  config:
    activate:
      on-profile: "!proxy"
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: "ca/keys/server_cert.pem"
            private-key: "ca/keys/server_key.pem"

server:
  port: 8443
  ssl:
    bundle: server
