#
# Configuration to use when the application is terminating TLS in the
# spring boot application itself.
#
spring:
  profiles:
    active: "!proxy"
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: "ca/keys/server_cert.pem"
            private-key: "ca/keys/server_key.pem"

server:
  port: 8443
  ssl:
    bundle: server

---
#
# Configuration to use when the application is running behind a proxy, that
# is terminating SSL connections. The proxy should send the
# x-forwarded-proto: https header to indicate that the original request was
# made using HTTPS. This configuration will cause Spring Boot application to
# consider that the request came in over a secure channel.
#
spring:
  profiles:
    active: proxy
server:
  forward-headers-strategy: native
  port: 8080