spring:
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: "ca/keys/server_cert.pem"
            private-key: "ca/keys/server_key.pem"

server:
  port: 8443
  ssl:
    bundle: server